### ISSUE TITLE
MackerNews is using libhn http://mackernews.com

### ISSUE THREAD

**Issue by hamin** [bennyguitar/libHN#24]
Just wanted to give a shout out :)

**Comment by hamin** [comment]
btw i'm the author of mackernews, opened up the pull request as the readme suggested so that you could add mackernews to the list of apps using it :) thanks again @bennyguitar  :)

**Comment by bennyguitar** [comment]
Awesome, it's on the readme now!

**Comment by hamin** [comment]
@bennyguitar thanks :)
