### ISSUE TITLE
Replying to a comment and a post is not working

### ISSUE THREAD

**Issue by jchomali** [bennyguitar/libHN#31]
Replying to a comment and a post is not working

**Comment by bennyguitar** [comment]
Fixed in `4.0.1` and now in the JSON Configuration as well :)

**Comment by jchomali** [comment]
Nice! Just implemented this update and it works like a charm!

Thank you!



Juan Carlos Chomali
iOS & Web Developer

**Comment by bennyguitar** [comment]
No problem man, you should be using 4.0.2 now since I noticed a problem with HNComments of the Job type.
