### ISSUE TITLE
HN changed their layout again

### ISSUE THREAD

**Issue by auto234875** [bennyguitar/libHN#34]
Top and New stories doesn't load.
 Best stories and Ask will load the titles but no comments.

**Comment by bennyguitar** [comment]
I've started updating the [JSON Configuration](/Source/hn.json) file to reflect the new layout, and posts seem to work, but comments need more work. I'm at work right now so I don't have a lot of time to mess with this right now. The easiest way to get this working would be to make changes to a local copy of hn.json and my News/YC app to make sure it works.

**Comment by bennyguitar** [comment]
Should be fixed now.

**Comment by hamin** [comment]
@bennyguitar ah confirmed its working now! Thanks again :) Also loving this new json configuration stuff :) Also I still owe u a copy of my mac app, where can i send you a redeem code?

**Comment by bennyguitar** [comment]
You can send one to brgordon@ua.edu and thanks for using my library!

**Comment by hamin** [comment]
@bennyguitar oh plz thanks for building it :). Just sent you the code to redeem the app from the Mac App Store :)
