### ISSUE TITLE
Comments are gone again

### ISSUE THREAD

**Issue by auto234875** [bennyguitar/libHN#35]
See title. I tested with proxy to be sure it isn't just slowbanned. 

News/YC is also not showing any comments.

**Comment by hamin** [comment]
Getting the same issue on my mac app

**Comment by bennyguitar** [comment]
Fixed again. If you check out this part of the [README](https://github.com/bennyguitar/libHN#json-configuration) you'll be able to see how the json configuration works and how posts/comments are created using that configuration.
