### ISSUE TITLE
First comment on posts does not show

### ISSUE THREAD

**Issue by nealyoung** [bennyguitar/libHN#36]
See this issue: https://github.com/nealyoung/HackerFeed/issues/5, I confirmed that this also occurs in other apps using libHN.

**Comment by jchomali** [comment]
Does anyone know why this might be happening?

**Comment by jchomali** [comment]
Don't worry, just found a fix. I will submit a PR right now

**Comment by jchomali** [comment]
Just submitted a PR fixing this.
