### ISSUE TITLE
Login is broken/crashes

### ISSUE THREAD

**Issue by hamin** [bennyguitar/libHN#43]
Hey @bennyguitar . I didn't realize this till recently but Login seems to be broken.

This is the crash:

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: aString != nil'
```

The crash from the logs occurs here:

```
MackerNews                           0x000000010d5438f3 __51-[HNManager loginWithUsername:password:completion:]_block_invoke (HNManager.m:126)
```

I was trying to debug and I can't tell what changed on HN site. Looking at the breakpoints I set its going here: https://github.com/bennyguitar/libHN/blob/master/Source/HNWebService.m#L210

On the HN website the login form is still use "act" & "pw" fields for the form. So yeah not sure what's going on. Happy to debug further if you have any insights

**Comment by jchomali** [comment]
I think the problem is in your app. My app is logging in users without problems.

**Comment by hamin** [comment]
@jchomali hmm I checked and my app code was passing the write credentials to the libHN login method, there was an returned from the HN login response. Let test again though

**Comment by hamin** [comment]
Lol sorry I was being an idiot. Closing issue :)
